import { Inter } from "next/font/google";
import "./globals.css";
import Aside from "../components/Aside";
import Header from "../components/Header";
import ProviderTheme from "@/components/themeProvider";
import ProviderSession from "@/components/providerSession";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
 title: "Movie App",
 description: "Generated by Meghdad",
};

export default function RootLayout({ children, session }) {
 return (
  <html dir="ltr" className="scroll-smooth" lang="en">
   <ProviderTheme>
    <body className={`scroll-smooth dark:bg-blue-950 ${inter.className}`}>
     <ProviderSession session={session}>
      <Toaster position='bottom-left' />
      <Aside />
      <div className=" container">
       <Header />
      </div>
      {children}
     </ProviderSession>
    </body>
   </ProviderTheme>
  </html>
 );
}
